### ISSUE TITLE
Unable to install sc-hsm-driver-x64 in Windows 10 

### ISSUE THREAD

**Issue by uae1972** [CardContact/sc-hsm-embedded#14]
Hi,
I am not able to install sc-hsm-driver-x64, it gives me an error failed to install the driver.
using the certutil -scinfo I able to test the certification and it recognized by the windows, and XCA is fully function and able to recognize the token as well.
if try to use IE to login to https://devnet.cardcontact.de/ the IE recognize the certification and it gives me choice, to select the reader however it display that Identiv uTrust 3522 embd SE Token, the smart card required drivers that are not present in this system. 
I also install the Firefox and I try to add the security device, and I am trying to select the c:\WINDOWS\System32\opensc-pkcs11.dll but is not shown in the folder to add in Firefox wizard, even I check myself in the System32 and both opensc-minidriver.dll and opensc-pkcs11.dll are there in the folder.
The windows regedit indicate 
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Cryptography\Calais\SmartCards\SmartCard-HSM-CL and HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Cryptography\Calais\SmartCards\SmartCard-HSM is correctly register.
Regards,
Amr

**Comment by CardContact** [comment]
Starting with V2.10 installation the driver installer is obsolete and replaced by the module installer.

Binaries for Windows are located under [Releases](https://github.com/CardContact/sc-hsm-embedded/releases).
