### ISSUE TITLE
File sc-hsm-minidriver.vcxproj not found

### ISSUE THREAD

**Issue by rafaelmembrives** [CardContact/sc-hsm-embedded#22]
File solution file sc-hsm-embedded.sln references to an inexistent sc-hsm-minidriver\sc-hsm-minidriver.vcxproj. ¿How can I build the minidriver?

Regards

**Comment by CardContact** [comment]
Fixed in  6e002d8

**Comment by rafaelmembrives** [comment]
The same for sc-hsm-minidriver-test.vcxproj

Thank you and my regards.

**Comment by CardContact** [comment]
Fixed in bd6342176669c38db80a82d1aa8736b6417baa8a

Sorry, hope all files are in now.

**Comment by rafaelmembrives** [comment]
Thank you so much, I finally managed to compile it succesfully with those files (only via command line since it did not work on Visual Studio 2017).

But isn't working the way I expect, the code is not invoked by Windows; I have included a MessageBox alert into CardAcquireContext function, but it is not shown. I have done the following:

* Used the project installer (it allocates the minidriver DLL into system32 folder).
* Replaced the sc-hsm-minidriver.dll with the one I have compiled including the visual alert.
* Opened a browser and opened a web with client-certificate authentication.
* The CardAcquireContext function is not invoked.

Am I maybe missing something? I am using Windows 10 just in case...

Regards.

**Comment by CardContact** [comment]
The browser is the last thing to try. First make sure that sc-hsm-minidriver-test and certutil -scinfo work. The browser does some strange things to access the minidriver, so chances are that you don't see the window because the browser blocks it.
