### ISSUE TITLE
Microsoft CSP-Minidriver 

### ISSUE THREAD

**Issue by johughes99** [CardContact/sc-hsm-embedded#32]
Can the Mini-drrver be built such that it calls another PKC#11 library - or is it set up so that it has to call the inbuilt PKCS#11 library?

**Comment by CardContact** [comment]
No. The PKCS#11 module and the CSP-Minidriver share code, but they don't build on top of each other.

**Comment by johughes99** [comment]
I have just been looking through the code - and realized that they build into a single dll.

Having the ability to load 3rd party PKCS#11 libraries something easy to do - and/or you are interested in?

I'm basically looking for a generic minidriver that can wrap a PKCS#11 library that supports read/write operations.  I suspect we may have to produce our own

**Comment by kategray** [comment]
@johughes99 How would you configure such a thing?  Put everything in the registry?

**Comment by johughes99** [comment]
I guess so.  The main thing you would need to do is to config the location of the pkcs#11 library
