### ISSUE TITLE
Not able to get CKA_VALUE with C_GetAttributeValue of a Secret Key

### ISSUE THREAD

**Issue by 7ritn** [CardContact/sc-hsm-embedded#37]
Hi,

I'm trying to extract the value of an AES Key, which is set to be extractable, via C_GetAttributeValue. However, I get as a return CKR_ATTRIBUTE_TYPE_INVALID which should not be happen since acording to the PKCS#11 specifications concerning the AES secret key object, the CKA_VALUE attribute should contain the key value. Since I can use the key to encrypt data it has to have a value.

I tested my code with the SoftHSMv2 and there I'm able to extract the key value.

**Comment by CardContact** [comment]
The SmartCard-HSM does not support AES key extraction in plain.

For extract a key value, the key object must be part of a key domain and the key value may be
wrapped under the Key Encryption Key. Use the Key Manager in the Smart Card Shell in order to do that.
